import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const alliance = localFont({
  src: [
    { path: "../assets/fonts/Alliance/Alliance-Regular.otf", weight: "400", style: "normal" },
    { path: "../assets/fonts/Alliance/Alliance-Bold.otf", weight: "700", style: "normal" },
    { path: "../assets/fonts/Alliance/Alliance-Black.otf", weight: "900", style: "normal" },
  ],
  variable: "--font-alliance",
});

export const metadata: Metadata = {
  title: "BioSystems Indonesia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={`${alliance.variable}`}>
        {children}
      </body>
    </html>
  );
}
